// WARNING - THIS FILE AUTOGENERATED
// Called with: output_settings(
//              num_delay_elements=3,
//              trigger_mode=triggered,
//              trigger_condition='GPIO4')

`define NUM_DELAY_ELEMENTS 3
`define TDC_DLYS_PER_TAP 1

//Define 'WE_NEVER', 'WE_ALWAYS', or 'WE_TRIGGERED'
`define WE_TRIGGERED

`define TRIGGER_CONDITION (GPIO4)
